apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Your email (for certificate expiry notifications)
    email: afzalkottukkal23@gmail.com
    
    # Secret to store the account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    
    # HTTP-01 challenge solver
    solvers:
    - http01:
        ingress:
          class: nginx